// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAq00CMi8WYmlfQKbEKlXh9rR8_t1U3nDE',
    appId: '1:325704926105:web:3bbdf44c5059224aeec908',
    messagingSenderId: '325704926105',
    projectId: 'movie-recommendation-sys-6ce14',
    authDomain: 'movie-recommendation-sys-6ce14.firebaseapp.com',
    storageBucket: 'movie-recommendation-sys-6ce14.firebasestorage.app',
    measurementId: 'G-RR24GDLTG2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCi5Vmy9_4sJ3yFz2pPCAmvHgH3MMyjLjA',
    appId: '1:325704926105:android:53236e782716f8fdeec908',
    messagingSenderId: '325704926105',
    projectId: 'movie-recommendation-sys-6ce14',
    storageBucket: 'movie-recommendation-sys-6ce14.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZMKNrUEBnky1nyDsvrXqKUKPKYqwgXho',
    appId: '1:325704926105:ios:50992a52533d74a3eec908',
    messagingSenderId: '325704926105',
    projectId: 'movie-recommendation-sys-6ce14',
    storageBucket: 'movie-recommendation-sys-6ce14.firebasestorage.app',
    iosBundleId: 'com.example.movio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZMKNrUEBnky1nyDsvrXqKUKPKYqwgXho',
    appId: '1:325704926105:ios:50992a52533d74a3eec908',
    messagingSenderId: '325704926105',
    projectId: 'movie-recommendation-sys-6ce14',
    storageBucket: 'movie-recommendation-sys-6ce14.firebasestorage.app',
    iosBundleId: 'com.example.movio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAq00CMi8WYmlfQKbEKlXh9rR8_t1U3nDE',
    appId: '1:325704926105:web:c020af0dff614d35eec908',
    messagingSenderId: '325704926105',
    projectId: 'movie-recommendation-sys-6ce14',
    authDomain: 'movie-recommendation-sys-6ce14.firebaseapp.com',
    storageBucket: 'movie-recommendation-sys-6ce14.firebasestorage.app',
    measurementId: 'G-E6XN8YETKC',
  );
}
